DROP TABLE IF EXISTS REMITTANCE;
CREATE TABLE REMITTANCE
(
    ID                 BIGINT IDENTITY PRIMARY KEY,
    CREATED_DATE       DATETIME,
    CREATED_BY         VARCHAR(50),
    LAST_MODIFIED_DATE DATETIME,
    LAST_MODIFIED_BY   VARCHAR(50),
    VERSION            int,
    REMIT_AMOUNT       int,
    REMIT_TYPE         VARCHAR(10),
    REMIT_CURRENCY     VARCHAR(10),
    BANK_CODE          VARCHAR(50),
    TRANSACTION_DATE   DATE
);

DROP TABLE IF EXISTS EVENT;
CREATE TABLE EVENT
(
    ID           BIGINT IDENTITY PRIMARY KEY,
    EVENT_TIME   DATETIME,
    EVENT_TYPE   VARCHAR(255),
    AGGREGATE_ID VARCHAR(50),
    EVENT        CLOB
);
