mimosa:
  web:
      strict: false
spring:
  application:
    name: data-jdbc
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE;MODE=Oracle
    username: ${DATABASE_USERNAME:sa}
    platform: h2
logging:
  level:
    sql: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    jdbc:
      resultsettable: INFO
      sqltiming: INFO
      sqlonly: FATAL
      audit: FATAL
      resultset: FATAL
      connection: FATAL
log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  trim:
    sql:
      extrablanklines: false
mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: tw.com.fcb.mimosa.examples

