server:
  port: 8081
spring:
  application:
    name: request testing
info.response.id: ${APP_ID:request-testing}
logging:
  level:
    tw.com.fcb.mimosa.web.APIRequestFilter: DEBUG
    web: DEBUG
mimosa:
  web:
    strict: true
    requestBufferSize: 8192
    requestBodyEncoding: UTF-8
  security:
    enabled: true
    strict: true
    backend-auth-service.url: "http://${server.address:localhost}:8080/backend-auth"
    ignoring:
      - method: options
        path:
          - "/**"
      - path:
          - "/v3/api-docs"
          - "/v3/api-docs/**"
          - "/swagger-ui"
          - "/swagger-ui/**"
          - "/h2"
          - "/h2/**"
          - "/actuator"
          - "/actuator/**"
          - "/swagger-ui.html"
          - "/backend-auth/**"
  tracing:
    extra:
      fields:
        - "transactionId"
        - "sourceId"
